apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-ci-demo
  labels:
    app: simple-ci-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-ci-demo
  template:
    metadata:
      labels:
        app: simple-ci-demo
    spec:
      containers:
      - name: simple-ci-demo
        image: aljics4/simple-ci-demo:latest
        ports:
        - containerPort: 8000
