apiVersion: v1
kind: Service
metadata:
  name: simple-ci-demo-service
spec:
  type: NodePort
  selector:
    app: simple-ci-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
