apiVersion: v1
kind: Service
metadata:
  name: simple-ci-demo-service
spec:
  selector:
    app: simple-ci-demo
  ports:
    - protocol: TCP
      port: 80          # port service
      targetPort: 8000  # port container Flask
  type: ClusterIP
