apiVersion: v1
kind: Service
metadata:
  name: simple-ci-demo 
spec:
  type: NodePort
  selector:
    app: simple-ci-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 
      nodePort: 30080
